name: engine
description: StonkFish chess engine 
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  fast_immutable_collections: ^9.1.5
  # path: ^1.8.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
